---
name: "ci-pr"

on:
    pull_request: {}

env:
    CI: true

jobs:
    run:
        runs-on: "ubuntu-20.04"

        steps:
            - uses: "actions/checkout@v1"
              with:
                  submodules: true
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "peaceiris/actions-hugo@v2"
              with:
                  hugo-version: "0.81.0"
                  extended: true
            - run: "make install"
            - run: "make lint"
            - run: "hugo --minify"
