---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d"
              with:
                  version: "latest"
            - uses: "actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v3"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "make lint"
            - run: "hugo --minify"
