---
name: "ci"

on:
    pull_request:
        branches:
            - "main"
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2"
              with:
                  version: "latest"
            - uses: "actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v3"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "make lint"
            - run: "hugo --minify"
