---
name: "deploy"

on:
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    deploy:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write"
        steps:
            - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2"
              with:
                  version: "latest"
            - uses: "actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v3"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "hugo --minify"
            - uses: "peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e"
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: "dbtedman/dbtedman.github.io"
                  publish_branch: "master"
                  publish_dir: ./public
