---
name: "deploy"

on:
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    deploy:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write"
        steps:
            - uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598"
              with:
                  version: "latest"
            - uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v2"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "hugo --minify"
            - uses: "peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7"
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: "dbtedman/dbtedman.github.io"
                  publish_branch: "master"
                  publish_dir: ./public
