---
name: "deploy"

on:
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    deploy:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write"
        steps:
            - uses: "actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd"
              with:
                  version: "latest"
            - uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v2"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "hugo --minify"
            - uses: "peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935"
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: "dbtedman/dbtedman.github.io"
                  publish_branch: "master"
                  publish_dir: ./public
