---
name: "deploy"

on:
    push:
        branches:
            - "main"

permissions: "read-all"

jobs:
    deploy:
        runs-on: "ubuntu-latest"
        permissions:
            contents: "write"
        steps:
            - uses: "actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b"
              with:
                  submodules: true
            - uses: "pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d"
              with:
                  version: "latest"
            - uses: "actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "peaceiris/actions-hugo@v3"
              with:
                  hugo-version: "0.105.0"
                  extended: true
            - run: "make install"
            - run: "hugo --minify"
            - uses: "peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e"
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  external_repository: "dbtedman/dbtedman.github.io"
                  publish_branch: "master"
                  publish_dir: ./public
